---
format: revealjs
---

## Today's Agenda {background-image="Images/background-forest_v3.png" .center}

```{r}
library(tidyverse)
library(kableExtra)
```

<br>

::: {.r-fit-text}
**It's time to pick our local environmental problem!**
:::

<br>

::: r-stack
Justin Leinaweaver (Spring 2025)
:::

::: notes
Prep for Class

1. Review and record participation submissions

<br>

**SLIDE**: ...
:::



## For Today {background-image="Images/background-forest_v3.png" .center}

<br>

Pick **ONE** local environmental problem and make **three arguments**:

1. This is an important public problem (with evidence)

2. It requires a collective decision (with evidence)

3. We should pick this as our focus for the semester because...

::: notes

Last class we presented our options as cleanly as possible

- e.g. details, not arguments

<br>

Today we make arguments!




Elevator pitches!




:::










## For Next Class {background-image="Images/background-forest_v3.png" .center}



::: notes
**Questions on the assignment?**

<br>

Keep thinking about your problem selection and let me know if you want to discuss it.
:::
