---
format: revealjs
---

## Today's Agenda {background-image="libs/Images/background-forest_v3.png" .center}

```{r}
library(tidyverse)
library(kableExtra)
library(readxl)
```

<br>

**I. The Basics of Problem-Solving in a Community**

<br>

Working on Paper 1

- Writing Workshop

<br>

::: r-stack
Justin Leinaweaver (Spring 2024)
:::

::: notes
Prep for Class

1. ...
:::


## Paper 1 {background-image="libs/Images/background-forest_v3.png" .center}

**Introducing the Problem**

<br>

Your report **must** include:

1. A description of the **scientific basis** for your problem,

2. An argument that this is a **public problem**,

3. An argument that this requires a **collective decision**, and

4. An analysis of **at least two stakeholders** with **opposing** viewpoints of the problem

::: notes

This week we are working on your first paper

- This description is posted on Canvas with additional details

- Please see the "Paper Submission Requirements" in the syllabus

<br>

**SLIDE**: Before I let you loose on the writing workshop, let's talk grading.
:::




## To be convincing an argument should be logical, clear, credible and critical {background-image="libs/Images/background-forest_v3.png" .center}

::: notes

This represents the heart of the rubric I use for grading written papers.

<br>

All of your written assignments in this class ask you to make arguments.

- Your goal for each is to write a convincing argument.

<br>

**SLIDE**: What does this mean?

:::



## Convincing arguments... {background-image="libs/Images/background-forest_v3.png" .center}

<br>

+ **Logical**: Do the premises support the conclusion?

+ **Clear**: Is the paper easy to read and understand?

+ **Credible**: Is there enough high quality evidence (cited using APA)?

+ **Critical**: Does the paper address weaknesses in the argument (e.g. logic, evidence, consider counter-arguments)?

::: notes

For grading, I basically read your paper and ask myself these four questions.

<br>

### Questions on the rubric or my expectations for your papers?

:::


## Paper 1 {background-image="libs/Images/background-forest_v3.png" .center}

**Introducing the Problem**

<br>

Your report **must** include:

1. A description of the **scientific basis** for your problem,

2. An argument that this is a **public problem**,

3. An argument that this requires a **collective decision**, and

4. An analysis of **at least two stakeholders** with **opposing** viewpoints of the problem

::: notes
**With the rubric in mind, any questions on the first paper?**

<br>

Today I want us to get and give feedback on a few of the projects in class.
- We'll reserve time at the end for writing/revision based on your work today

<br>

I want to emphasize that this is a SUPER valuable exercise
- Diving deeply into someone else's project will help you immeasurably with your own.

- See what works, what doesn't and help them find gaps in their arguments.

<br>

*Split Class into Pairs*

Ok, pairs, take 10 minutes to focus on ONE of the projects.
- Discuss where you are and then both of you spend the time focused on that project.

<br>

### Make sense?

- Go!

<br>

Ok, swap projects and now take 10 minutes on the other one!

<br>

*New pairs and repeat exercise!*
- 10 mins, person 1
- 10 mins, person 2

<br>

Let's now use the rest of our time to reflect on what you've done today and polish your own work!

:::


## For Next Class {background-image="libs/Images/background-forest_v3.png" .center}

<br>

See the syllabus for readings on "command and control" policy designs

::: notes

Next week we shift into the next section of the class focused on policy design options

- e.g. what are some of the more popular or common approaches to solving environmental problems

<br>

We begin with "command and control" policies next week.

:::


