---
format: revealjs
---

## {background-image="Images/background-forest_v3.png" .center}

```{r}
library(tidyverse)
library(kableExtra)
```

**Welcome to the representatives from:**

- The President's Council on Sustainability

- Think Green!

- The Student Government Association

<br>

**Our Topic**

- How well equipped is Drury to solve environmental problems?


::: notes
Prep for Class

1. Let's grab the tall chairs from the hallway and set them up along the window facing the class

<br>

Welcome all and thank you so much to the reps for joining us today!

- Our class is currently gathering information on our community and the environmental problems we face

- The plan is to select a specific problem and spend the second half of the semester working to address it

<br>

Each of you belongs to a group, or has a role, that gives you some very interesting experience of dealing with problem-solving on Drury's campus

- Our hope is to learn more about what you do and what you see on our campus to help us in our work moving forward

<br>

**To start, would each of you introduce yourselves and tell us a bit about your group and its role on campus?**

**What are the most pressing (short-term) environmental concerns you have about campus?**

**What are the longer-term concerns or big-picture needs you see on our campus?**

**What has been your experience of problem-solving on campus? Any advice for getting things done or obstacles to avoid?**

**In what ways are we doing a good job connecting to the student body on these issues? How could we do this better?**


:::








