---
format: revealjs
---

## Today's Agenda {background-image="Images/background-forest_v3.png" .center}

```{r}
library(tidyverse)
library(kableExtra)
```

<br>

::: {.r-fit-text}
**It's time to pick our environmental problem!**
:::

<br>

<br>

::: r-stack
Justin Leinaweaver (Spring 2026)
:::

::: notes
Prep for Class

1. Review and record participation submissions.

2. Publish the Google Links for class on Canvas Modules for today (AFTER CLASS STARTS)
    
    - Form: 04-2 Selecting our Environmental Problem
    
    - Doc: 04-2 Environmental Problem Options
    
3. Markers x 4

<br>

We have a big job today!

- **SLIDE**: Let's select the environmental problem we plan to work on for the rest of the semester!

:::



## For Today {background-image="Images/background-forest_v3.png" .center}

<br>

Pick **ONE** local environmental problem and make **three arguments**:

1. This is an important public problem (with evidence)

2. It requires a collective decision (with evidence)

3. We should pick this as our focus for the semester because...

::: notes

We used our time last class to build a big list of options

- We broke these down into some of the components that we would need to explore if we chose that problem

<br>

For today I asked each of you to reflect on this list and then to prepare an argument in favor of one of these problems.

- **How did that go?**

<br>

**SLIDE**: Time to review the options

:::



## {background-image="Images/background-forest_v3.png" .center}

::: {.r-fit-text}

**Selecting our Environmental Problem:**

1. Review the options

2. Select three and vote

:::
::: notes

On Canvas I have published two URL links for you

- *Publish links on Canvas*

- Link 1 takes you to an anonymized list of all the arguments submitted for today

- Link 2 takes you to a Google form for recording our votes

<br>

Your job is to review and reflect on all of the arugments on the document and then to vote for your three top three choices using the form

- **Any questions?**

- Let's go!

<br>

*Organize the next steps*

1. Review the responses and identify the top 3 or 4

2. Split class into that number of groups (force them to work in NEW groups!)

3. Assign one of the top arguments to each group

:::





## {background-image="Images/background-forest_v3.png" .center}

::: {.r-fit-text}
**Diagram three arguments on the board:**

1. Therefore, X is an **important** problem

2. Therefore, X is an **public** problem

3. Therefore, X requires a **collective decision**
:::
::: notes

Groups, take 15 minutes to get these three arguments on the board

- Start with what was submitted on Canvas and then MAKE IT STRONGER!

- Go!

<br>

*PRESENT and DISCUSS each*

<br>

- **How difficult would this problem be for us given the community we live in?**

- **How difficult would this problem be for us given the time available?**

- **How difficult would this problem be for us given the complexity of the problem?**

<br>

*OPEN DISCUSSION*

- **Ok, what is our selected environmental problem?**

<br>

**SLIDE**: With that selected let's talk about your first report for the semester

:::



## {background-image="Images/background-forest_v3.png" .center}

::: {.r-fit-text}
**Outcome 1: Baseline Argument Report**
:::

<br>

Make a three premise argument that we have an environmental problem to address in our community:

- Premise 1 - This is an important problem

- Premise 2 - This is a public problem

- Premise 3 - The problem should be addressed collectively

::: notes

*Read slide details*

- Note that the paper is due at the end of week 7 and our in-class work over the next three weeks should help you think about the problem more deeply.

<br>

Assignment details are currently available on Canvas.

- Each premise should be explained, supported by evidence and critically analyzed

- All evidence must be cited using APA formatted in-text citations and be included in a bibliography

- The paper must be a minimum of 850 words (not counting the bibliography)

- The paper is due Feb 28th

<br>

**Questions on the assignment?**

<br>

*With time remaining*

With our remaining time let's all focus on strengthening the these arguments on the board for our selected problem!

- Go!

:::




## For Next Class {background-image="Images/background-forest_v3.png" .center}

<br>

::: {.r-fit-text}

**Exploring problem-solving processes**

- Three readings

- Canvas assignment

:::

::: notes

Next week I want us to review a series of readings from the literature meant to help you think about processes for solving problems in a community

- Tuesday we'll review a series of textbook approaches from different disciplines

- Thursday we get to read Ostrom's work on CPR management

<br>

**Questions on the assignment?**

<br>

Canvas: Designing a plan of attack for solving problems in our community

- What are THREE key elements you argue are necessary to successfully navigate a domestic policy-making process? 

- Make sure to fully explain each point. 

- Each element may be a bullet point, but even bullet points must be in complete sentences

:::
