---
format: revealjs
---

# Today's Agenda {background-image="libs/Images/background-forest_v3.png" }

```{r}
library(tidyverse)
library(readxl)
```

<br>

Exploring the Success Stories

- Adaptive Governance

<br>

::: r-stack
Justin Leinaweaver (Spring 2024)
:::

::: notes
Prep for Class

1. Review submitted cases
:::



## Paper 2 {background-image="libs/Images/background-forest_v3.png"  .center}

<br>

Which of the four policy approaches is the "right" one for you?

- Analyze the pros and cons of each option **SEPERATELY** for your chosen environmental problem

::: notes
Keep your eye on the next target: Paper 2.

- In that paper you will be asked to evaluate all four of the approaches we study in class from the perspective of your chosen environmental problem.

### Questions on the paper so far?

<br>

Today we analyze our final policy approach using your real world success cases.
:::



## Assignment for Today {background-image="libs/Images/background-forest_v3.png"  .center}

<br>

Submit to Canvas a real world example of **this approach** being used to **successfully** address an environmental problem **similar to the one in your project**.

**Present as an argument**: This case shows that addressing environmental problem X can be done successfully using adaptive governance approaches.

::: notes
Let's review all the cases for APA format.
:::



## Assignment for Today {background-image="libs/Images/background-forest_v3.png" .center}

<br>

**This case shows that we can use adaptive governance to address environmental problem X.**

- What aspect of your problem does this policy focus on?

- Which stakeholders does it target? How?

- What institutions support this policy?

::: notes
Take five minutes to reflect on your argument and get ready to present it to other people as answers to these three questions.

- Problem: Specific, narrow aspect targeted by this tax?

- Stakeholders: What does it require them to do?

- Institutions: What rules or structures currently exists to make this possible?

<br>

### Questions on this?

<br>

Get to it!

<br>

Welcome to our environmental policy cocktail party!

- We will now take 25 minutes to mingle, present our cases and hear everybody elses' cases.

<br>

I don't want to see groups of three!
- Your job is to interact in pairs.

- I want pairs focused on hearing one case and presenting one case at a time.

<br>

### Questions?

- Go!

<br>

*You mingle too.*

- *This was super fun and you got to help steer students to being more specific, more precise*

<br>

*Split class into three groups*

- Go sit with your group and claim some space on the board
:::



## Assignment for Today {background-image="libs/Images/background-forest_v3.png"  .center}

<br>

What is your **best advice for policymakers** considering **adaptive governance** for environmental problem-solving?

- Types of problems?

- Types of stakeholders?

- Types of institutional support?

::: notes
You've just heard a bunch of cases where adaptive governance successfully addressed an environmental problem. 

- I want you to use those cases as your data and draw out inferences from them

- What advice can we offer policymakers who are considering adaptive governance for environmental problem-solving

<br>

I'm going to ask you to think about this as three distinct categories of problem and work on each one separately

- **SLIDE**
:::



## Analyzing the Cases {background-image="libs/Images/background-forest_v3.png" .center}

**Problem Types**

<br>

Think about all of the specific problems you heard today and use them to make a list:

- Adaptive governance works well when targeting problems that look like...

::: notes

To begin, focus only on the types of problem you heard about in the cases

- We'll get to the stakeholders and institutional supports in a moment.

<br>

*ON THE BOARD*: Make me a list of problem characteristics that lend themselves to being solved with adaptive governance.

<br>

### Questions?

- Get to it!

<br>

#### Notes
(Class: date?)
- ?
:::



## Analyzing the Cases {background-image="libs/Images/background-forest_v3.png" .center}

**Stakeholder Types**

<br>

Think about all of the specific problems you heard today and use them to make a list:

- Adaptive governance works well when targeting stakeholders that look like...

::: notes

Ok, repeat your list making but now focus on the stakeholders

- What kinds of stakeholders does adaptive governance work well on?

<br>

### Questions?

- Get to it!

<br>

#### Notes
(Class: 3/3/2022)
- ?
:::



## Analyzing the Cases {background-image="libs/Images/background-forest_v3.png"  .center}

**Institutional Support**

<br>

How much institutional support is required for adaptive governance to be effective?

- e.g. who did the rule-making, the monitoring, the enforcement, etc.?

::: notes

Last job is to think about the complexity of implementing adaptive governance.

- How much institutional support, and what kinds, is required for adaptive governance to be effective?

<br>

### Questions?

- Get to it!

<br>

Groups, go take a look at what the other groups proposed!

- Read it all and ask questions if you need clarifications
:::



## Best advice / things to remember when designing "green" subsidies? {background-image="libs/Images/13-1-Huerta_Murcia_v2.png"}

::: notes
Bottom line time.

### In a practical sense, what guidance can we offer policy-makers considering using adaptive governance to solve environmental problems?

<br>

*ON BOARD as a CLASS*
- ?

<br>

**Ok, everybody take five minutes to reflect on our work today.**

Jot down some notes that I promise you'll need when it comes time to write the next paper.

- What are the pros and cons of using this approach for your specific problem?
:::



## Would adaptive governance work well for your project? {background-image="libs/Images/13-1-Huerta_Murcia_v2.png"}

::: notes
**Which principle would be easiest to implement as part of your design? Why?**

<br>

### Which principle would be most difficult to implement as part of your design? Why?

<br>

### Could any of these work on their own for your project? Why or why not?
:::



## Paper 2 {background-image="libs/Images/background-forest_v3.png"  .center}

<br>

Which of the four policy approaches is the "right" one for you?

- Analyze the pros and cons of each option **SEPERATELY** for your chosen environmental problem

::: notes
Next week we work on the paper!

In this paper you will be asked to evaluate all four of the approaches we study in class from the perspective of your chosen environmental problem.

<br>

**SLIDE**: To set us up for this paper...
:::



## Assignment for Next Class {background-image="libs/Images/background-forest_v3.png"  .center}

<br>

**Before class** submit a start to your evaluation of the four policy options from class. 
- Define your environmental problem

- What is one strong "pro" for using each of the policy options to address your environmental problem?

::: notes
Each answer should be AT LEAST one complete sentence.

<br>

Next week we explore processes of policy-making and problem-solving.

### Questions on the assignment?
:::

