---
format: revealjs
---

# Today's Agenda {background-image="libs/Images/background-forest_v3.png" }

```{r}
library(tidyverse)
library(readxl)
```

<br>

::: {.r-fit-text}
**Paper 2: Review and Revise Drafts**
:::

<br>

::: r-stack
Justin Leinaweaver (Spring 2024)
:::

::: notes
Prep for Class

1. Send out reminder that next week we meet in Springfield Hall Lab A to work on posters
:::



## Next Week {background-image="libs/Images/background-forest_v3.png" .center}

<br>

Meet in Springfield Hall Lab A to work on converting Paper 2 into a Fusion Day poster

::: notes
Next week we take your material from the second paper and use it to prepare a Fusion Day poster.

- So we'll meet in the computer lab to kick things off next week
:::




## Paper 2 {background-image="libs/Images/background-forest_v3.png" .center}

<br>

Which of the four policy design options is the "right" choice for addressing your environmental problem?

- Analyze the pros and cons of each option for your chosen problem

::: notes
**Questions on the prompt?**

<br>

**Everybody have a rough draft?**
:::


## Paper Rubric {background-image="libs/Images/background-forest_v3.png" .center}

<br>

**To be convincing an argument should be logical, clear, credible and critical.**

::: notes
TBD
:::


## Convincing arguments... {background-image="libs/Images/background-forest_v3.png" .center}

<br>

+ **Logical**: Do the premises support the conclusion?

+ **Clear**: Is the paper easy to read and understand?

+ **Credible**: Is there enough high quality evidence (cited using APA)?

+ **Critical**: Does the paper address weaknesses in the argument (e.g. logic, evidence, consider counter-arguments)?

::: notes
Ok, everybody, get some feedback, give some feedback and get to writing!
:::



