---
format: revealjs
---

## Today's Agenda {background-image="Images/background-forest_v3.png" .center}

```{r}
library(tidyverse)
library(kableExtra)
library(readxl)
```

<br>

::: {.r-fit-text}

**Meeting with Local Advocates**

:::

- The James River Basin Partnership

- Missouri Guardrails

- Missouri Prairie Foundation



<br>

::: r-stack
Justin Leinaweaver (Spring 2026)
:::

::: notes
Prep for Class

1. Record Canvas submissions

<br>

Quick reminders and announcements

- **SLIDE**

:::



## Thursday (Apr 2) {background-image="Images/background-forest_v3.png" .center}

<br>

**River Clean-up (9:30a - 11:30a)**

- Meet at the pavilion at Silver Springs Park (1100 N. Hampton Ave)

- Wear appropriate shoes (ideally ones they don't mind getting a little wet) and bring a reusable water bottle

- You MUST complete the waiver and bring it



## Next Week {background-image="Images/background-forest_v3.png" .center}

<br>

**Analyzing Complex Problems (I)**

- Tuesday: The Role of Risk in Decision-making

- Thursday: The Role of Uncertainty in Environmental Problem-solving

::: notes

Over the next three classes I want to introduce you to some of the literature that will help us think about the variation in our stakeholders and our problems

- Thursday we talk risk

- Next week we talk uncertainty and collective action problems

:::



## Welcome to our Guests! {background-image="Images/background-forest_v3.png" .center}

<br>

**The James River Basin Partnership**

- Brooke Widmar, Education Outreach Manager

**Missouri Guardrails**

- Kathy Christy and Dan Chiles

**Missouri Prairie Foundation**

- Clifford Barratt, Prairie Stewardship Assistant

::: notes


1. Would you tell us how your group was formed and how you came to join it?

2. I'd like the students to hear about the challenges in creating and sustaining an organization like yours. Would you be willing to tell us about your day-to-day operations?
- e.g. Are you member-driven? How much fundraising do you do? How large is your staff and how large would you like it to be?

3. What are you currently most focused on in terms of community problems?

4. Would you share with us any policy or collaboration successes we can learn from?

5. What advice would you offer to young advocates looking to make a difference in our community? (e.g. sources of authority, primary movers and shakers, obstacles to be aware of)

6. How could we get involved with you in the future? Where can the students plug into your work?

:::



## {background-image="Images/background-forest_v3.png" .center}

::: {.r-fit-text}
**Overcoming the Collective Action Problem**

- How was your group formed?

- What was your path to the group?

:::


## {background-image="Images/background-forest_v3.png" .center}

::: {.r-fit-text}
**Running an Organization**

- Are you member-driven? 

- How much fundraising do you do? 

- How large is your FT staff?

:::



## {background-image="Images/background-forest_v3.png" .center}

### What are you currently most focused on in terms of community problems?



## {background-image="Images/background-forest_v3.png" .center}

### Would you share with us any policy or collaboration successes we can learn from?



## {background-image="Images/background-forest_v3.png" .center}

### What advice would you offer to young advocates looking to make a difference in our community? 

- (e.g. sources of authority, primary movers and shakers, obstacles to be aware of?)



## {background-image="Images/background-forest_v3.png" .center}

### How could we get involved with you in the future? 

- Where can the students plug into your work?


