---
format: revealjs
---

## Today's Agenda {background-image="Images/background-forest_v3.png" .center}

```{r}
library(tidyverse)
library(kableExtra)
library(readxl)
```

<br>

::: {.r-fit-text}

**Finding and Analyzing the Relevant Stakeholders**

- Finalizing your stakeholder map of the problem

- Working on the framing report

- *Sit with your group*

:::

<br>

::: r-stack
Justin Leinaweaver (Spring 2025)
:::

::: notes
Prep for Class

1. Record Canvas submissions

<br>

As you come in, sit in your groups!

<br>

**SLIDE**: Our current step in the process

:::



## {background-image="Images/background-forest_v3.png" .center}

:::: {.r-fit-text}
**Engaging Productively as Problem-Solvers**

1) **Describe** the problem facing our community

2) **Investigate** the relevant stakeholders

3) **Frame** the problem for the stakeholders

4) **Design** a policy to address the problem

5) Take **action** to push the plan forward!

::::

::: notes

Over the last few weeks we have:

- Narrowed down each group's problem definition,

- Designed a map of the problem that specifies the types of relevant stakeholders

- AND collected specific examples of stakeholders in our community identified by that map

<br>

**SLIDE**: Let's start by taking some time to report back to your group on what you've found

:::


## {background-image="Images/background-forest_v3.png" .center}

::: {.r-fit-text}

**Filling in your Stakeholder Map**

1. Who are they?

2. Connections to the flow of food waste?

3. Evidence of previous engagement?

:::

::: notes

Groups we'll start today by making sure everybody is in the loop on what you found.

- Share with the rest of your group what you learned about the two stakeholders you researched

- Spend some time on each one and help your group see how this fills in your map

- Go! (*Give them plenty of time to do this*)

<br>

Ok groups, let's check-in on your maps

<br>

**Is everyone confident they have a useful map of their problem in our community? e.g. all key types of stakeholders identified**

<br>

**Does each group have multiple examples of specific stakeholders for each of the types in their map?**

<br>

**Are you confident you have sufficient variation within each type to be able to draw inferences about the wider community?**

<br>

**SLIDE**: Ok, the next step requires talking about the second report

:::



## {background-image="Images/background-forest_v3.png"}

::: {.r-fit-text}
**OUTCOME 2**

**The Problem Framing Report (Due Apr 11)**
:::

<br>

### The purpose of this paper is to reframe the "call to action" argument you made in the last report for the stakeholders you identified as relevant in your map of our community.

::: notes

Big picture...

- *Read the slide*

<br>

Your second paper is an exercise in tailoring your argument to generate buy-in for collective action from specific groups.

<br>

Your goal remains the same!

- Make a convincing argument that our community has an important, public environmental problem that should be addressed collectively.

<br>

HOWEVER! The test is how well that argument explicitly accounts for the preferences of the specific stakeholders you are working with

- If you want their help, OR for them to change their behavior, you better frame the problem in a way they like!

- e.g. Stakeholder Type A's businesses depend on tourism so an "importance" or "public problem" argument might focus on those interests 

- e.g. Stakeholder Type B worries about invasive government regulations so your "collective decision" argument will need to adapt to that

<br>

**Questions on the big picture here?**

<br>

**SLIDE**: Add key notes

:::



## {background-image="Images/background-forest_v3.png"}

::: {.r-fit-text}
**OUTCOME 2**

**The Problem Framing Report (Due Apr 11)**
:::

<br>

**Notes**

- All claims connect to your stakeholders

- All claims supported by evidence

- All evidence cited using APA

- Minimum 1,000 words

::: notes

*Read slide*

<br>

Make sure you make the framing EXPLICIT in the text

- Don't assume the reader is in your head (e.g. knows how your claims connect to the stakeholders)
    
- As you adapt each part of your argument be clear who that is meant to draw support from

<br>
    
BUT, don't present this as manipulation!
    
- Your report is being designed to be read by your stakeholders

- This is NOT a secret plan to trick those stakeholders
    
- **Distinction make sense?**

<br>

Note also the slightly longer required word count

- Based on your first reports I don't think this will be a problem for anybody in class

<br>

**Questions on the assignment?**

<br>

**SLIDE**: Assignment for next class

:::



## For Next Class {background-image="Images/background-forest_v3.png" .center}

::: {.r-fit-text}

**Previewing your Problem Framing**

<br>

Where is the overlap across your stakeholders in terms of:

- The importance of this problem?

- The public nature of this problem?

- The need for a collective decision on this problem?

:::

::: notes

This is part of what I want you to submit before next class

- The rest of the assignment is on Canvas

<br>

Groups, let's use the rest of our time today to start trying to find the overlap in your stakeholders view of the problem.

- Use each other to brainstorm and bounce ideas around

<br>

**Questions on the assignment?**

- Go!

:::
