---
format: revealjs
---

## Today's Agenda {background-image="Images/background-forest_v3.png" .center}

```{r}
library(tidyverse)
library(kableExtra)
library(readxl)
```

<br>

::: {.r-fit-text}

**Analyzing Drury's Food Waste Problems**

- Reporting back on the relevant stakeholders

:::

<br>

::: r-stack
Justin Leinaweaver (Spring 2025)
:::

::: notes
Prep for Class

1. Record Canvas submissions

2. Be ready to show them the Fusion panel slides

<br>

**SLIDE**: Before we dig into Drury, we need to design tomorrow's Fusion Day capstone!

:::



## Fusion Day (Apr 23) Capstone Panel {background-image="Images/background-forest_v3.png" .center .smaller}

- 20 minute presentation

- What are the courses in the certificate? (me: 3 mins)

- Introduce capstone topic (me: 1 minute)
    - Why is food waste important in SGF? (Student 1: 2 mins)
    - Why is it a public problem? (Student 2: 2 mins)
    - Why do we need a collective decision? (Student 3: 2 mins)
    - Policy examples to address the problem (1 example per student, 1 min each)

- Q&A (7 mins)


::: notes

Task: We have 20 minutes to present the work of the certificate and answer questions

<br>

Let me show you the basic slides I have made for tomorrow

- *Show them the panel slides*

<br>

*Split class into three groups, one group per volunteer*

- *Decide which student will do which prompt*

<br>

GROUPS, help the volunteer map out what they should cover in their 2 minutes

- Work directly on the board so we can ensure no significant overlap between them

- Go!

<br>

*REPORT back and DISCUSS*

<br>

**What policy examples do we want to briefly highlight?**

- **We need three!**

<br>

**Volunteers, do you feel ready? Any questions or concerns?**

<br>

**SLIDE**: Let's shift our focus back to Drury!

:::



## Food Waste at Drury University {background-image="Images/background-forest_v3.png" .center}

:::: {.r-fit-text}
1) **Describe** the problem facing our community

2) **Investigate** the relevant stakeholders

3) **Frame** the problem for the stakeholders

4) **Design** a policy to address the problem

5) Take **action** to push the plan forward!

::::

::: notes

Ok, last class we turned our focus to Drury.

<br>

**What CPR did we decide to focus on?**

- (**SLIDE**)

:::



## Food Waste at Drury University {background-image="Images/background-forest_v3.png" .center}

<br>

::: {.r-fit-text}
**Describe** the problem facing our community

- System: Drury student community

- Units: Food waste (lb)

:::

::: notes

We're focusing on students as a community that produces food waste

<br>

**What are the different types of student we identified in our quick map of this community?**

- (*ON BOARD so we can discuss the sample*)

- Dorms (no kitchen)

- Dorms (with kitchen)

- Those living in Greek housing

- Commuters living at home

- Commuters living on their own

- Diners in the Commons

- Diners in the CX

- Diners at Einstein Bagels

<br>

**SLIDE**: Stakeholder work for today

:::



## Food Waste at Drury University {background-image="Images/background-forest_v3.png" .center}

<br>

::: {.r-fit-text}
**Investigate** the Relevant Stakeholders

- How do they view the problem?

- How do they contribute to the problem?

- What are the obstacles to changing their behavior?

:::

::: notes

Ok, to start everybody take some time to review all of the stakeholder data submitted by the class

- Let's get familiar with the data!

<br>

Ok, our first big questions have to focus on sample selection

<br>

**Do we have representative cases for each of the types in our stakeholder map?**

- **Some better represented than others?**

<br>

**Any new somewhat distinct groups you want to add to the map based on your experience gathering this data?**

<br>

Now we clearly don't have a random sample of Drury students so generalizing about the population is very risky

- **In what specific ways do we have to be cautious when analyzing this sample of stakeholders?**

- **In other words, what forms of selection bias might be at play here?**

<br>

**SLIDE**: Alright, let's work our way through the results

:::



## {background-image="Images/background-forest_v3.png" .center}

::: {.r-fit-text}
**Investigating the Relevant Stakeholders**
:::

<br>

### Q1. When you think about the challenges facing the Drury community, what are the most important issues that come to mind?

::: notes

**What do we learn about Drury and our student community from Q1?**

- (*ON BOARD*)

<br>

*Other important lessons here about our community?**

<br>

**SLIDE**: Q2

:::



## {background-image="Images/background-forest_v3.png" .center}

::: {.r-fit-text}
**Investigating the Relevant Stakeholders**
:::

<br>

### Q2. Do you believe that food waste, meaning food that is sent to the landfill without being consumed, deserves to be on the list of most important issues facing Drury? Why or why not?

::: notes

**How did the respondents respond to being prompted into considering food waste as an "important" problem?**

- **Any surprising reactions?**

<br>

**SLIDE**: Q3

:::



## {background-image="Images/background-forest_v3.png" .center}

::: {.r-fit-text}
**Investigating the Relevant Stakeholders**
:::

<br>

### Q3. In the last week, have you taken any specific actions meant to minimize the amount of food you purchase that gets sent to the landfill without being consumed? For example, taking smaller portions in the dining hall, bringing home leftovers, donating excess food to a shelter, participating in a composting program, etc.?

::: notes

**Help me list the specific actions taken?**

- (*ON BOARD*)

<br>

**Did you believe all the responses you got here?**

- **Any social desirability bias here?**

<br>

**SLIDE**: Q4

:::



## {background-image="Images/background-forest_v3.png" .center}

::: {.r-fit-text}
**Investigating the Relevant Stakeholders**
:::

<br>

### Q4. In what specific ways have you noticed that Drury tries to help you minimize your personal production of food waste? Have those efforts been effective? Why or why not?

::: notes

**What do we learn about the students we interviewed from Q4?**

<br>

**What do we learn about Drury from the answers given to Q4?**

<br>

**SLIDE**: Q5

:::



## {background-image="Images/background-forest_v3.png" .center}

::: {.r-fit-text}
**Investigating the Relevant Stakeholders**
:::

<br>

### Q5. What kind of incentive would be necessary for you to agree to join a composting program on campus (e.g. make a commitment to compost all of your food waste for an entire semester)?

::: notes

**Incentives suggested?**

- **What do we learn from these ideas?**

<br>

**SLIDE**: Problem framing
:::



## Food Waste at Drury University {background-image="Images/background-forest_v3.png" .center}

<br>

::: {.r-fit-text}
**Framing** the problem for the stakeholders

- Importance

- Public Problem

- Collective Decision
:::

::: notes

Ok, taking on board all of this information, let's try to unpack a problem framing that would convince most students on campus that food waste is an important and public problem that requires collective action.

- Talk to the people around you and get ready to report back on the elements you think our framing would need to include

<br>

*REPORT back and DISCUSS each*

<br>

**SLIDE**: For next class

:::



## For Next Class {background-image="Images/background-forest_v3.png" .center}

<br>

Propose an action we could take on campus **NEXT WEEK** to reduce the amount of food waste produced by students. 

- Make sure to explicitly connect this to the data we collected and analyzed last class

- Explain the action AND why you believe it would be effective

- Don't forget, policy doesn't require formal rules or government to be effective!



