---
format: revealjs
---

## Today's Agenda {background-image="Images/background-forest_v3.png" .center}

```{r}
library(tidyverse)
library(kableExtra)
library(readxl)
```

<br>

::: {.r-fit-text}

**Analyzing Drury's Food Waste Problems**

- TBD

:::

<br>

::: r-stack
Justin Leinaweaver (Spring 2025)
:::

::: notes
Prep for Class

1. Record Canvas submissions

<br>

**SLIDE**: ...

:::




## Food Waste at Drury University {background-image="Images/background-forest_v3.png" .center}

:::: {.r-fit-text}
1) **Describe** the problem facing our community

2) **Investigate** the relevant stakeholders

3) **Frame** the problem for the stakeholders

4) **Design** a policy to address the problem

5) Take **action** to push the plan forward!

::::

::: notes


<br>

**SLIDE**: ...

:::



## Food Waste at Drury University {background-image="Images/background-forest_v3.png" .center}

<br>

:::: {.r-fit-text}
**Describe** the problem facing our community

- Let's brainstorm the food waste CPRs on campus

::::

::: notes


<br>

**SLIDE**: ...

:::



## For Next Class {background-image="Images/background-forest_v3.png" .center}

<br>

::: {.r-fit-text}

TBD

:::

::: notes


<br>

**Questions on the assignment?**

:::
