---
format: revealjs
---

# Today's Agenda {background-image="libs/Images/background-forest_v3.png" }

```{r}
library(tidyverse)
library(readxl)
```

<br>

::: {.r-fit-text}

**Work on the Final Policy Proposal**

- Due May 8th, 3pm

:::

<br>

::: r-stack
Justin Leinaweaver (Spring 2024)
:::

::: notes
Prep for Class

1. ...

:::



## Assignment 5: Proposing a Policy {background-image="libs/Images/background-forest_v3.png" .center}

<br>

Propose a policy to address your selected environmental problem that balances the interests of the relevant stakeholders against the constraints of established institutions and uncertainty.

::: notes

**Questions on the prompt?**

:::




## A convincing policy proposal: {background-image="libs/Images/background-forest_v3.png" .center}

- Advances your policy recommendation in **EVERY** paragraph,

- Includes a clear and compelling problem definition,

- Identifies and appeals to specific stakeholders,

- Considers the complications, and

- Offers guidance for measuring its effectiveness over time.

::: notes

My thoughts on the elements of a convincing policy proposal.

- **Any questions on the key elements of a convincing proposal?**

:::




## {background-image="libs/Images/background-forest_v3.png" .center}

::: {.r-fit-text}
**One Approach to the Final Policy Proposal**
:::

1. Actor X should do Y because problem Z is important

2. Actor X should do Y because it is adapted to the science of the problem

3. Actor X should do Y because it will appeal to the key stakeholders

4. Actor X should do Y because it is adapted to the uncertainties in the problem

5. Actor X should do Y because we can evaluate its effectiveness over time

::: notes

My thoughts on one possible outline for the final paper

- **Any questions on this as an outline?**

<br>

Alright, the time today is for you to work on the final paper

- Let's dive in!

:::












